# Generated by Django 4.2.2 on 2023-06-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_set', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
