# Generated by Django 4.2.2 on 2023-06-30 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_set', '0004_alter_account_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='collectdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder_set.account', to_field='email_address')),
            ],
        ),
    ]
