# Generated by Django 4.2.2 on 2023-06-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_set', '0005_collectdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectdata',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
